//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> Gender { get; set; }
        public string DOB { get; set; }
    }
}
